# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fake_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=1000)),
                ('birthday', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('pokes', models.ManyToManyField(related_name='poked_by', through='portal_app.Pokes', to='portal_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='pokes',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_poker', to='portal_app.User'),
        ),
        migrations.AddField(
            model_name='pokes',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_victim', to='portal_app.User'),
        ),
    ]
